services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_DB: baseDB
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede

volumes:
  postgres_data:

networks:
  minha_rede:
